### ISSUE TITLE
[Bug] Create graph often runs into a Server Error

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#144] opened 2022-04-06 09:59 UTC
When creating a new graph in the result view, the page often runs into a server error. I guess it happens because the chosen parameters can't be displayed in the chosen graph. 

I just tried it with the following example and received a server error:

Scenario
Szenario 4 - S01 + PV + Wind + Batterie

Report Type
Installed and optimized capacities

Energy vector
Electricity

Components
Wind -Erweiterung
Versorgungsnetz_consumption
PV - Frei
Batterie_capacitiy

**Comment by Bachibouzouk** [comment] 2022-04-06 10:06
This is because create graph is in development :)

**Comment by Bachibouzouk** [comment] 2022-04-06 12:31
This was because change induced in #143 `"optimizedAddCap"` was renamed `"optimized_add_cap"` but I still needed to go in the database and perform the change there as well. It was present in Simulation.results but also in AssetsResults.assets_list (which is some duplicate of Simulation.results but only of asset results and formatted a bit differently, it belongs to legacy code I haven't modified yet, but maybe I will)

**Closed** 2022-04-07 22:30 UTC
Labels: bug, frontend, results
